# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Just Deploy to Heroku

on: [workflow_dispatch]
permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Show Secrets
      run: |
        echo ${{ secrets.AWS_ACCESS_KEY_ID }}
        echo ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        echo ${{ secrets.HEROKU_API_KEY }}
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
        role-session-name: UdMlopsDaSessionName
    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: "3.8"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Test with pytest
      run: |
        pytest
    - name: Set up DVC
      uses: iterative/setup-dvc@v1
    - name: Pull DVC
      run: |
        cd data
        dvc pull
    - name: Build and push
      uses: akhileshns/heroku-deploy@v3.12.12
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        heroku_app_name: "da-census-uda-heroku"
        heroku_email: "diego.amicabile@gmail.com"
    - name: Config Heroku for AWS
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        heroku_app_name: "da-census-uda-heroku"
        heroku_email: "diego.amicabile@gmail.com"
      run: heroku config:set AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}



